In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../../../../OneDrive - University of Edinburgh/Development/Adaptive_market_portfolio/data/processed/crsp_market_data_v2.csv')

C:\Users\chris\AppData\Local\Temp\ipykernel_25740\2618822374.py:1: DtypeWarning: Columns (7,11,14) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../../../../OneDrive - University of Edinburgh/Development/Adaptive_market_portfolio/data/processed/crsp_market_data_v2.csv')

In [3]:
data

,PERMNO,date,SHRCD,TICKER,COMNAM,TRDSTAT,PERMCO,CUSIP,DLSTCD,FACPR,...,ASK,SHROUT,CFACPR,CFACSHR,sprtrn,ABS_PRC,MidPrice,ADJ_ABS_PRC,MKTCAP,last_date
0,61487,2003-12-29,11.0,AE,ADAMS RESOURCES & ENERGY INC,A,59,635130.0,NaN,NaN,...,13.75,4218.0,1.000,1.000,0.012401,13.51,13.630,13.51,56985.18,2023-12-29
1,61487,2003-12-30,11.0,AE,ADAMS RESOURCES & ENERGY INC,A,59,635130.0,NaN,NaN,...,13.90,4218.0,1.000,1.000,0.000144,13.83,13.890,13.83,58334.94,2023-12-29
2,61487,2003-12-31,11.0,AE,ADAMS RESOURCES & ENERGY INC,A,59,635130.0,NaN,NaN,...,13.69,4218.0,1.000,1.000,0.002055,13.55,13.620,13.55,57153.90,2023-12-29
3,61487,2004-01-02,11.0,AE,ADAMS RESOURCES & ENERGY INC,A,59,635130.0,NaN,NaN,...,13.83,4218.0,1.000,1.000,-0.003094,13.83,13.765,13.83,58334.94,2023-12-29
4,61487,2004-01-05,11.0,AE,ADAMS RESOURCES & ENERGY INC,A,59,635130.0,NaN,NaN,...,13.67,4218.0,1.000,1.000,0.012395,13.66,13.615,13.66,57617.88,2023-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20831289,91453,2008-08-08,11.0,MAQ,MARATHON ACQUISITION CORP,A,51099,Y2718360,NaN,NaN,...,7.62,49411.0,0.125,0.125,0.023893,7.61,7.615,60.88,376017.71,2008-08-14
20831290,91453,2008-08-11,11.0,MAQ,MARATHON ACQUISITION CORP,A,51099,Y2718360,NaN,NaN,...,7.61,49411.0,0.125,0.125,0.006943,7.61,7.605,60.88,376017.71,2008-08-14
20831291,91453,2008-08-12,11.0,MAQ,MARATHON ACQUISITION CORP,A,51099,Y2718360,NaN,NaN,...,7.30,49411.0,0.125,0.125,-0.012051,7.28,7.290,58.24,359712.08,2008-08-14
20831292,91453,2008-08-13,11.0,MAQ,MARATHON ACQUISITION CORP,A,51099,Y2718360,NaN,NaN,...,7.27,49411.0,0.125,0.125,-0.002916,7.24,7.255,57.92,357735.64,2008-08-14
20831293,91453,2008-08-14,11.0,MAQ,MARATHON ACQUISITION CORP,A,51099,Y2718360,NaN,NaN,...,7.46,49411.0,0.125,0.125,0.005522,7.33,7.405,58.64,362182.63,2008-08-14

In [4]:
data.columns

Index(['PERMNO', 'date', 'SHRCD', 'TICKER', 'COMNAM', 'TRDSTAT', 'PERMCO',
       'CUSIP', 'DLSTCD', 'FACPR', 'DLPRC', 'DLRET', 'PRC', 'VOL', 'RET',
       'BID', 'ASK', 'SHROUT', 'CFACPR', 'CFACSHR', 'sprtrn', 'ABS_PRC',
       'MidPrice', 'ADJ_ABS_PRC', 'MKTCAP', 'last_date'],
      dtype='object')